version: '3.9'
services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"  # Rasa port

  flask:
    build:
      context: .
      # dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Flask port